name: project-automation

on:
  issues:
    types: [opened, labeled, unlabeled]
  pull_request:
    types: [opened, reopened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.event.action }}


      - name: move 'new' PR to 'Review in progress'
        uses: alex-page/github-project-automation-plus@v0.2.2
        if: |
          github.event_name == 'pull_request' &&
          (
            github.event.action == 'opened' ||
            github.event.action == 'reopened'
          )
        with:
          project: Backlog
          column: Review in progress
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: move new issue or unlabeled to 'To do'
        uses: alex-page/github-project-automation-plus@v0.2.2
        if: |
          github.event_name == 'issue' &&
          (
            github.event.action == 'opened' ||
            (
              github.event.action == 'unlabeled' &&
              !contains(github.event.issue.labels.*.name, 'Status: Em Progresso')
            )
          )
        with:
          project: Backlog
          column: To do
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: move issue labeled to 'In progress'
        uses: alex-page/github-project-automation-plus@v0.2.2
        if: |
          github.event_name == 'issue' &&
          (
            contains(github.event.issue.labels.*.name, 'Status: Em Progresso')
          )
        with:
          project: Backlog
          column: In progress
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: move issue labeled to 'Blocked'
        uses: alex-page/github-project-automation-plus@v0.2.2
        if: |
          github.event_name == 'issue' &&
          (
            contains(github.event.issue.labels.*.name, 'Status: Bloqueado')
          )
        with:
          project: Backlog
          column: Blocked
          repo-token: ${{ secrets.GH_TOKEN }}